# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" connections (from the same machine)
# The official Postgres images use this for internal processes and entrypoint scripts.
local   all             all                                     trust

# Connections from any other machine, e.g., your host machine
# or other containers on the same network.
# 'all' means all databases, 'all' means all users.
# '0.0.0.0/0' means all IPv4 addresses.
# 'scram-sha-256' is a secure password-based authentication method.
host    all             all             0.0.0.0/0               scram-sha-256